# Generated by Django 3.2.4 on 2021-07-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210715_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
